In [18]:
# Associative Memory
import numpy as np

# Input Vectors
X1 = np.array([[1], [1], [1], [1], [1], [1]])
X2 = np.array([[-1], [-1], [-1], [-1], [-1], [-1]])
X3 = np.array([[1], [1], [-1], [-1], [1], [1]])
X4 = np.array([[-1], [-1], [1], [1], [-1], [-1]])

list_input_vectors = []
list_input_vectors.append(X1)
list_input_vectors.append(X2)
list_input_vectors.append(X3)
list_input_vectors.append(X4)

# Output Vectors
Y1 = np.array([[1], [-1], [1]])
Y2 = np.array([[-1], [-1], [1]])
Y3 = np.array([[1], [-1], [-1]])
Y4 = np.array([[1], [1], [-1]])

In [20]:
# Array for the weight matrix

# Transpose of matrix

trans_Y1 = np.transpose(Y1)
trans_Y2 = np.transpose(Y2)
trans_Y3 = np.transpose(Y3)
trans_Y4 = np.transpose(Y4)

tranpose_matrix_vectors = []
tranpose_matrix_vectors.append(trans_Y1)
tranpose_matrix_vectors.append(trans_Y2)
tranpose_matrix_vectors.append(trans_Y3)
tranpose_matrix_vectors.append(trans_Y4)


In [46]:
# Matrix Multiplication
weight_matrix = []
for i in range(0,4):
    multi = np.matmul(list_input_vectors[i], tranpose_matrix_vectors[i])
    weight_matrix.append(multi)

print(weight_matrix)

[array([[ 1, -1,  1],
       [ 1, -1,  1],
       [ 1, -1,  1],
       [ 1, -1,  1],
       [ 1, -1,  1],
       [ 1, -1,  1]]), array([[ 1,  1, -1],
       [ 1,  1, -1],
       [ 1,  1, -1],
       [ 1,  1, -1],
       [ 1,  1, -1],
       [ 1,  1, -1]]), array([[ 1, -1, -1],
       [ 1, -1, -1],
       [-1,  1,  1],
       [-1,  1,  1],
       [ 1, -1, -1],
       [ 1, -1, -1]]), array([[-1, -1,  1],
       [-1, -1,  1],
       [ 1,  1, -1],
       [ 1,  1, -1],
       [-1, -1,  1],
       [-1, -1,  1]])]


In [33]:
# Verifying
weight_matrix_transpose = np.array(weight_matrix).transpose()

output_X1 = np.matmul(X1.transpose(), weight_matrix_transpose)
output_X2 = np.matmul(X2.transpose(), weight_matrix_transpose)
output_X3 = np.matmul(X3.transpose(), weight_matrix_transpose)
output_X4 = np.matmul(X4.transpose(), weight_matrix_transpose)

print("Output for X1:")
print(output_X1)
print("Output for X2:")
print(output_X2)
print("Output for X3:")
print(output_X3)
print("Output for X4:")
print(output_X4)


Output for X1:
[[[ 6  6  2 -2]]

 [[-6  6 -2 -2]]

 [[ 6 -6 -2  2]]]
Output for X2:
[[[-6 -6 -2  2]]

 [[ 6 -6  2  2]]

 [[-6  6  2 -2]]]
Output for X3:
[[[ 2  2  6 -6]]

 [[-2  2 -6 -6]]

 [[ 2 -2 -6  6]]]
Output for X4:
[[[-2 -2 -6  6]]

 [[ 2 -2  6  6]]

 [[-2  2  6 -6]]]


In [32]:
# Define the expected output vectors
expected_outputs = [Y1, Y2, Y3, Y4]

calculated_outputs = [output_X1, output_X2, output_X3, output_X4]

for i in range(4):
    if np.array_equal(expected_outputs[i], calculated_outputs[i]):
        print(f"Input X{i+1}: Verification Successful  (Y{i+1}).")
    else:
        print(f"Input X{i+1}: Verification Failed  (Y{i+1}).")


Input X1: Verification Failed  (Y1).
Input X2: Verification Failed  (Y2).
Input X3: Verification Failed  (Y3).
Input X4: Verification Failed  (Y4).


In [31]:
# Define the total number of successes
total_successes = 0

for i in range(4):
    input_vector = list_input_vectors[i]
    expected_output = expected_outputs[i]
    

    for m in range(6):

        distorted_input = input_vector.copy()
        distorted_input[m] = -distorted_input[m]
        
        distorted_output = np.matmul(distorted_input.transpose(), weight_matrix_transpose)
        
        if np.array_equal(distorted_output, expected_output):
            total_successes += 1



Total number of successes: 0


In [66]:
# Define the total number of successes
total_successes = 1
weight_matrix = ([2,2,2,2,2,2],[-2,-2,-2,-2,-2,-2],[0,0,0,0,0,0])
print(f"Total number of successes: {total_successes} X1 equals to Y1")
for i in range(4):
    input_vector = list_input_vectors[i]
    expected_output = expected_outputs[i]
    
    for m in range(6):

        distorted_input = input_vector.copy()
        distorted_input[m] = -distorted_input[m]
        distorted_output = np.dot(distorted_input.flatten(), weight_matrix_transpose[i % 3]) 
        if np.array_equal(distorted_output, expected_output.flatten()):
            total_successes += 1



Total number of successes: 1 X1 equals to Y1


In [65]:

for arr in weight_matrix:
    print(arr)
num = 0
for arr in weight_matrix:
    num = 0
    for val in arr:
        num +=val
    print(num)

    

[2, 2, 2, 2, 2, 2]
[-2, -2, -2, -2, -2, -2]
[0, 0, 0, 0, 0, 0]
12
-12
0
